// Auto-generated from public/leet-code.xlsx (Sheet1). Do not edit by hand.
import type { Problem } from './coding';

export const problems: Problem[] = [
  {
    number: 643,
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/maximum-average-subarray-i/",
  },
  {
    number: 1456,
    title: "Maximum Number of Vowels in a Substring of Given Length",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/",
  },
  {
    number: 1343,
    title: "Number of Sub-arrays of Size K and Average ≥ Threshold",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/number-of-sub-arrays-of-size-k-and-average-threshold/",
  },
  {
    number: 567,
    title: "Permutation in String",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/permutation-in-string/",
  },
  {
    number: 438,
    title: "Find All Anagrams in a String",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
  },
  {
    number: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
  },
  {
    number: 209,
    title: "Minimum Size Subarray Sum",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/minimum-size-subarray-sum/",
  },
  {
    number: 1004,
    title: "Max Consecutive Ones III",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/max-consecutive-ones-iii/",
  },
  {
    number: 424,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/longest-repeating-character-replacement/",
  },
  {
    number: 904,
    title: "Fruit Into Baskets",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/fruit-into-baskets/",
  },
  {
    number: 76,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/minimum-window-substring/",
  },
  {
    number: 239,
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/sliding-window-maximum/",
  },
  {
    number: 1493,
    title: "Longest Subarray of 1's After Deleting One Element",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/",
  },
  {
    number: 1658,
    title: "Minimum Operations to Reduce X to Zero",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/",
  },
  {
    number: 1208,
    title: "Get Equal Substrings Within Budget",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Sliding Window",
    leetcodeUrl: "https://leetcode.com/problems/get-equal-substrings-within-budget/",
  },
  {
    number: 125,
    title: "Valid Palindrome",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/valid-palindrome/",
  },
  {
    number: 167,
    title: "Two Sum II – Input Array Is Sorted",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
  },
  {
    number: 15,
    title: "3Sum",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/3sum/",
  },
  {
    number: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/container-with-most-water/",
  },
  {
    number: 42,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/trapping-rain-water/",
  },
  {
    number: 283,
    title: "Move Zeroes",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/move-zeroes/",
  },
  {
    number: 26,
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
  },
  {
    number: 80,
    title: "Remove Duplicates from Sorted Array ||",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/",
  },
  {
    number: 27,
    title: "Remove Element",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/remove-element/",
  },
  {
    number: 392,
    title: "Is Subsequence",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/is-subsequence/",
  },
  {
    number: 844,
    title: "Backspace String Compare",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/backspace-string-compare/",
  },
  {
    number: 977,
    title: "Squares of a Sorted Array",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/squares-of-a-sorted-array/",
  },
  {
    number: 18,
    title: "4Sum",
    difficulty: "—",
    severity: 'info',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/4sum/",
  },
  {
    number: 16,
    title: "3Sum Closest",
    difficulty: "—",
    severity: 'info',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/3sum-closest/",
  },
  {
    number: 88,
    title: "Merge Sorted Array",
    difficulty: "—",
    severity: 'info',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/merge-sorted-array/",
  },
  {
    number: 75,
    title: "Sort Colors",
    difficulty: "—",
    severity: 'info',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/sort-colors/",
  },
  {
    number: 55,
    title: "Jump Game",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Greedy",
    leetcodeUrl: "https://leetcode.com/problems/jump-game/",
  },
  {
    number: 1752,
    title: "Check if Array Is Sorted and Rotated",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Circular Array / Count Breaks (Order Violations)",
    leetcodeUrl: "https://leetcode.com/problems/check-if-array-is-sorted-and-rotated/",
  },
  {
    number: 1,
    title: "Two Sum",
    difficulty: "Easy",
    severity: 'success',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/two-sum/",
  },
  {
    number: 217,
    title: "Contains Duplicate",
    difficulty: "Easy",
    severity: 'success',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/contains-duplicate/",
  },
  {
    number: 219,
    title: "Contains Duplicate II",
    difficulty: "Easy",
    severity: 'success',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/contains-duplicate-ii/",
  },
  {
    number: 220,
    title: "Contains Duplicate III",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/contains-duplicate-iii/",
  },
  {
    number: 49,
    title: "Group Anagrams",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/group-anagrams/",
  },
  {
    number: 128,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/longest-consecutive-sequence/",
  },
  {
    number: 347,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/top-k-frequent-elements/",
  },
  {
    number: 380,
    title: "Insert Delete GetRandom O(1)",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/insert-delete-getrandom-o1/",
  },
  {
    number: 36,
    title: "Valid Sudoku",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "HashMap",
    leetcodeUrl: "https://leetcode.com/problems/valid-sudoku/",
  },
  {
    number: 1480,
    title: "Running Sum of 1d Array",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/running-sum-of-1d-array/",
  },
  {
    number: 303,
    title: "Range Sum Query - Immutable",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/range-sum-query-immutable/",
  },
  {
    number: 724,
    title: "Find Pivot Index",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/find-pivot-index/",
  },
  {
    number: 560,
    title: "Subarray Sum Equals K",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/subarray-sum-equals-k/",
  },
  {
    number: 525,
    title: "Contiguous Array",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/contiguous-array/",
  },
  {
    number: 523,
    title: "Continuous Subarray Sum",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/continuous-subarray-sum/",
  },
  {
    number: 974,
    title: "Subarray Sums Divisible by K",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/subarray-sums-divisible-by-k/",
  },
  {
    number: 930,
    title: "Binary Subarrays With Sum",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/binary-subarrays-with-sum/",
  },
  {
    number: 1248,
    title: "Count Number of Nice Subarrays",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/count-number-of-nice-subarrays/",
  },
  {
    number: 238,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Prefix Sum",
    leetcodeUrl: "https://leetcode.com/problems/product-of-array-except-self/",
  },
  {
    number: 94,
    title: "Binary Tree Inorder Traversal",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-inorder-traversal/",
  },
  {
    number: 144,
    title: "Binary Tree Preorder Traversal",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-preorder-traversal/",
  },
  {
    number: 145,
    title: "Binary Tree Postorder Traversal",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-postorder-traversal/",
  },
  {
    number: 102,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
  },
  {
    number: 104,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
  },
  {
    number: 111,
    title: "Minimum Depth of Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/minimum-depth-of-binary-tree/",
  },
  {
    number: 226,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/invert-binary-tree/",
  },
  {
    number: 100,
    title: "Same Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/same-tree/",
  },
  {
    number: 101,
    title: "Symmetric Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/symmetric-tree/",
  },
  {
    number: 110,
    title: "Balanced Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/balanced-binary-tree/",
  },
  {
    number: 543,
    title: "Diameter of Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/diameter-of-binary-tree/",
  },
  {
    number: 112,
    title: "Path Sum",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/path-sum/",
  },
  {
    number: 113,
    title: "Path Sum II",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/path-sum-ii/",
  },
  {
    number: 257,
    title: "Binary Tree Paths",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-paths/",
  },
  {
    number: 129,
    title: "Sum Root to Leaf Numbers",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/sum-root-to-leaf-numbers/",
  },
  {
    number: 437,
    title: "Path Sum III",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/path-sum-iii/",
  },
  {
    number: 124,
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
  },
  {
    number: 199,
    title: "Binary Tree Right Side View",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-right-side-view/",
  },
  {
    number: 515,
    title: "Find Largest Value in Each Tree Row",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/find-largest-value-in-each-tree-row/",
  },
  {
    number: 103,
    title: "Binary Tree Zigzag Level Order Traversal",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
  },
  {
    number: 236,
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/",
  },
  {
    number: 572,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/subtree-of-another-tree/",
  },
  {
    number: 297,
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
  },
  {
    number: 105,
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
  },
  {
    number: 106,
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/",
  },
  {
    number: 114,
    title: "Flatten Binary Tree to Linked List",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/",
  },
  {
    number: 116,
    title: "Populating Next Right Pointers in Each Node",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/",
  },
  {
    number: 230,
    title: "Kth Smallest Element in a BST",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
  },
  {
    number: 98,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/validate-binary-search-tree/",
  },
  {
    number: 700,
    title: "Search in a Binary Search Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/search-in-a-binary-search-tree/",
  },
  {
    number: 701,
    title: "Insert into a Binary Search Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/insert-into-a-binary-search-tree/",
  },
  {
    number: 450,
    title: "Delete Node in a BST",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/delete-node-in-a-bst/",
  },
  {
    number: 235,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
  },
  {
    number: 108,
    title: "Convert Sorted Array to Binary Search Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/",
  },
  {
    number: 173,
    title: "Binary Search Tree Iterator",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-search-tree-iterator/",
  },
  {
    number: 404,
    title: "Sum of Left Leaves",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/sum-of-left-leaves/",
  },
  {
    number: 222,
    title: "Count Complete Tree Nodes",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/count-complete-tree-nodes/",
  },
  {
    number: 637,
    title: "Average of Levels in Binary Tree",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/average-of-levels-in-binary-tree/",
  },
  {
    number: 662,
    title: "Maximum Width of Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/maximum-width-of-binary-tree/",
  },
  {
    number: 958,
    title: "Check Completeness of a Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/check-completeness-of-a-binary-tree/",
  },
  {
    number: 513,
    title: "Find Bottom Left Tree Value",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/find-bottom-left-tree-value/",
  },
  {
    number: 1026,
    title: "Maximum Difference Between Node and Ancestor",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/",
  },
  {
    number: 988,
    title: "Smallest String Starting From Leaf",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/smallest-string-starting-from-leaf/",
  },
  {
    number: 863,
    title: "All Nodes Distance K in Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/",
    notes: `<h2>Problem</h2>
<p>
  Given the <strong>root</strong> of a binary tree, the value of a <strong>target</strong> node, and an
  integer <code>k</code>, return an array of the values of all nodes that have a distance <code>k</code>
  from the target node.
</p>
<img src="/images/leet-code-863.svg" alt="Tree with target node 5 and highlighted nodes at distance K" />
<h2>Approach</h2>
<ol>
  <li>Treat the tree as an <strong>undirected graph</strong>: store each node's parent while running an initial DFS.</li>
  <li>Start a <strong>BFS</strong> from the target node, marking visited nodes so we never walk back up.</li>
  <li>Collect the values of every node reached at <strong>exactly level k</strong>.</li>
</ol>
<h2>Complexity</h2>
<ul>
  <li><strong>Time:</strong> O(n)</li>
  <li><strong>Space:</strong> O(n)</li>
</ul>
<h2>Code</h2>
<pre><code>function distanceK(root, target, k) {
  // 1) Build parent pointers with a DFS.
  const parent = new Map();
  const dfs = (node, par) =&gt; {
    if (!node) return;
    parent.set(node, par);
    dfs(node.left, node);
    dfs(node.right, node);
  };
  dfs(root, null);

  // 2) BFS outward from target, never revisiting nodes.
  const result = [];
  const seen = new Set([target]);
  let queue = [target];
  let dist = 0;
  while (queue.length &amp;&amp; dist &lt;= k) {
    const next = [];
    for (const node of queue) {
      if (dist === k) result.push(node.val);
      for (const nb of [node.left, node.right, parent.get(node)]) {
        if (nb &amp;&amp; !seen.has(nb)) {
          seen.add(nb);
          next.push(nb);
        }
      }
    }
    queue = next;
    dist++;
  }
  return result;
}</code></pre>`,
  },
  {
    number: 652,
    title: "Find Duplicate Subtrees",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/find-duplicate-subtrees/",
  },
  {
    number: 889,
    title: "Construct Binary Tree from Preorder and Postorder Traversal",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/",
  },
  {
    number: 2096,
    title: "Step-By-Step Directions From a Binary Tree Node to Another",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/",
  },
  {
    number: 1448,
    title: "Count Good Nodes in Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
  },
  {
    number: 1302,
    title: "Deepest Leaves Sum",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/deepest-leaves-sum/",
  },
  {
    number: 1372,
    title: "Longest ZigZag Path in a Binary Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/",
  },
  {
    number: 1315,
    title: "Sum of Nodes with Even-Valued Grandparent",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/sum-of-nodes-with-even-valued-grandparent/",
  },
  {
    number: 530,
    title: "Minimum Absolute Difference in BST",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/minimum-absolute-difference-in-bst/",
  },
  {
    number: 783,
    title: "Minimum Distance Between BST Nodes",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/minimum-distance-between-bst-nodes/",
  },
  {
    number: 653,
    title: "Two Sum IV - Input is a BST",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/",
  },
  {
    number: 669,
    title: "Trim a Binary Search Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/trim-a-binary-search-tree/",
  },
  {
    number: 109,
    title: "Convert Sorted List to Binary Search Tree",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/",
  },
  {
    number: 96,
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/unique-binary-search-trees/",
  },
  {
    number: 95,
    title: "Unique Binary Search Trees II",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/unique-binary-search-trees-ii/",
  },
  {
    number: 337,
    title: "House Robber III",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/house-robber-iii/",
  },
  {
    number: 968,
    title: "Binary Tree Cameras",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/binary-tree-cameras/",
  },
  {
    number: 834,
    title: "Sum of Distances in Tree",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/sum-of-distances-in-tree/",
  },
  {
    number: 987,
    title: "Vertical Order Traversal of a Binary Tree",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/",
  },
  {
    number: 2458,
    title: "Height of Binary Tree After Subtree Removal Queries",
    difficulty: "Hard",
    severity: 'danger',
    pattern: "Binary Tree",
    leetcodeUrl: "https://leetcode.com/problems/height-of-binary-tree-after-subtree-removal-queries/",
  },
  {
    number: 268,
    title: "Missing Number",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Arithmetic Progression",
    leetcodeUrl: "https://leetcode.com/problems/missing-number/",
  },
  {
    number: 448,
    title: "Find All Numbers Disappeared in an Array",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Mark index with minus",
    leetcodeUrl: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
  },
  {
    number: 1365,
    title: "How Many Numbers Are Smaller Than the Current Number",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Frequency array if numbers have range",
    leetcodeUrl: "https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/",
  },
  {
    number: 1266,
    title: "Minimum Time Visiting All Points",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Math Abs, Min, Max",
    leetcodeUrl: "https://leetcode.com/problems/minimum-time-visiting-all-points/",
  },
  {
    number: 867,
    title: "Transpose Matrix",
    difficulty: "Easy",
    severity: 'success',
    pattern: "Matrix",
    leetcodeUrl: "https://leetcode.com/problems/transpose-matrix/",
  },
  {
    number: 189,
    title: "Rotate Array",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "No Pattern",
    leetcodeUrl: "https://leetcode.com/problems/rotate-array/",
  },
  {
    number: 430,
    title: "Flatten a Multilevel Doubly Linked List",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Double Link List",
    leetcodeUrl: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
  },
  {
    number: 150,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    severity: 'warn',
    leetcodeUrl: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
  },
  {
    number: 443,
    title: "String Compression",
    difficulty: "Medium",
    severity: 'warn',
    pattern: "Two Pointers",
    leetcodeUrl: "https://leetcode.com/problems/string-compression/",
  },
  {
    number: 845,
    title: "Longest Mountain in Array",
    difficulty: "Medium",
    severity: 'warn',
    leetcodeUrl: "https://leetcode.com/problems/longest-mountain-in-array/",
  },
];
